name: Build and Package Electron App

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: workflows/checkout@v3

      - name: Set up Node.js
        uses: workflows/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build and package for Windows
        run: yarn build:win

      - name: Upload artifact
        uses: workflows/upload-artifact@v3
        with:
          name: ExamShowboard-Windows
          path: dist/*.exe
