name: Build and Package Electron App

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build and package for Windows
        run: yarn build:win

      - name: Upload artifact
        uses: @actions/upload-artifact@v4
        with:
          name: ExamShowboard-Windows
          path: dist/*.exe
